### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-JoseABCruz#1]

**Comment by JoseABCruz** [comment]
[Infografia Unidad 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-JoseABCruz/files/14184801/Infografia.Unidad.1.pdf)

**Comment by Gregorio012** [comment]
Muy bien 20

**Comment by Gregorio012** [comment]
Muy bien 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
